# File: .docker/docker-compose.yml
version: '3'

services:
  python:
    build:
      context: ..
      dockerfile: Dockerfile.python
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../:/litreview
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/litreview
      # Add any environment variables you need
    networks:
      - litreview-network

  latex:
    build:
      context: ..
      dockerfile: Dockerfile.latex
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../src:/litreview/src
      - ../output:/litreview/output
      - ../figures:/litreview/figures
      - texmf-data:/usr/local/texlive
    ports:
      - "3000:3000"  # For LaTeX Workshop if needed
    working_dir: /litreview
    networks:
      - litreview-network

networks:
  litreview-network:

volumes:
  texmf-data:
