# File: .docker/docker-compose.yml
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../notebook/:/container_workspace
    ports:
      - "8888:8888"

  latex_dod:
      user: "${UID:-1000}:${GID:-1000}"
      build:
        context: ..
        dockerfile: .docker/Dockerfile.latex 
      volumes:
        - ../latex/src:/project/src
        - ../latex/output:/project/output
        - ../latex/figures:/project/figures
        - ../latex/include:/project/include
      ports:
        - "3000:3000"  # For LaTeX Workshop
      working_dir: /project
      command: tail -f /dev/null
